backend:
  name: git-gateway
  branch: Cms-v1

media_folder: 'public/assets' # Folder where user uploaded files should go
public_folder: ' /assets'

collections: # A list of collections the CMS should be able to edit
  - name: 'post' # Used in routes, ie.: /admin/collections/:slug/edit
    label: 'Post' # Used in the UI, ie.: "New Post"
    folder: 'src/pages/blog' # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    delete: true
    fields: # The fields each document in this collection have
      - {label: "Layout", name: "layout", widget: "hidden", default: "../../layouts/blogLayout.astro"}
      - {label: "Featured Image", name: "thumbnail", widget: "image"}
      - { label: 'Title', name: 'title', widget: 'string' }
      - { label: 'Description', name: 'description', widget: 'text' }
      - { label: 'Summary', name: 'summary', widget: 'text' }      
      - {label: "Card Image", name: "avatar", widget: "image"}
      - { label: 'Body', name: 'body', widget: 'markdown' }
      - { label: 'Author', name: 'author', widget: 'string' }
      - { label: 'Publish Date', name: 'date', widget: 'date' , format: 'MMM Do YY' }
      - { label: 'Tags', name: 'tag', widget: 'list' }
        